# Generated by Django 5.0 on 2025-11-24 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("web", "Web Application"),
                            ("mobile", "Mobile App"),
                            ("api", "API Service"),
                            ("iot", "IoT System"),
                            ("cloud", "Cloud Infrastructure"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tech_stack",
                    models.CharField(
                        help_text="e.g., Django, React, PostgreSQL", max_length=255
                    ),
                ),
                (
                    "scale",
                    models.CharField(
                        help_text="e.g., small, medium, large system", max_length=255
                    ),
                ),
                (
                    "budget",
                    models.PositiveIntegerField(help_text="Estimated available budget"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
