# Generated by Django 5.0 on 2025-11-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_projectanalysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="budget",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="scale",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(max_length=255),
        ),
    ]
