# Generated by Django 5.0 on 2025-11-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_project_budget_alter_project_scale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectanalysis",
            name="risk_category",
            field=models.CharField(default="Unknown", max_length=20),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="security_score",
            field=models.IntegerField(default=0),
        ),
    ]
