# Generated by Django 5.0 on 2025-11-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_projectanalysis_risk_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectanalysis",
            name="executive_summary",
            field=models.TextField(blank=True),
        ),
    ]
